### PR TITLE
revert(ophan)!: Revert add `key_event_card` ophan component type

### PR DESCRIPTION
**Pull request by joecowton1**
Reverts guardian/libs#348

We no longer need this change, see this comment: https://github.com/guardian/dotcom-rendering/pull/4856#pullrequestreview-967516855

### CODE REVIEW

**Comment by sndrs** [comment]
this would be a breaking change i think? you can do `fix!` to trigger that I think

**Comment by joecowton1** [comment]
> this would be a breaking change i think? you can do `fix!` to trigger that I think

Ah yes you're right, should be fixed now.

**Comment by mxdvl** [comment]
Alternatively, mark it as deprecated, and remove it in another version, if you don't need this to trigger a major release.

**Comment by joecowton1** [comment]
> Alternatively, mark it as deprecated, and remove it in another version, if you don't need this to trigger a major release.

Happy to do either, though I imagine it may get forgotten if we don't remove it now. What is your preference @sndrs ?

**Review by jamesgorrie — APPROVED** [review]

**Comment by jamesgorrie** [comment]
I'd go with triggering a major release - any changes in the client will be simple enough and avoids creating tech debt.

**Comment by sndrs** [comment]
agree with @jamesgorrie – let's own this change :)

**Review by sndrs — APPROVED** [review]

**Pull request merged**
