### PR TITLE
feat(format)!: split up `ArticleDesign.Media`

### PR DESCRIPTION
**Pull request by JamieB-gu**
## What does this change?

This change removes `ArticleDesign.Media` and replaces it with `ArticleDesign.Gallery`, `ArticleDesign.Audio` and `ArticleDesign.Video`.

**BREAKING CHANGE:** Consumers of `ArticleFormat` and/or `ArticleDesign` will need to update to handle this change. This may involve updating component props, fixtures, `switch` and `if` statements, etc.

## Why?

The designs for gallery, audio and video pieces look quite different to one another. Trying to capture them all within `ArticleDesign.Media` may not give us enough flexibility to differentiate in our UI code. 

Audio and video seem similar, but there are a number of differences, including:

- Order of the main media and standfirst
- Styling of the standfirst
- Podcast image in the left column
- Colours and lines
- The mini epic on audio pieces
- "More ways to listen" on audio pieces

Galleries look considerably different, and include features like:

- An immersive-style header
- Captions in the left column
- Images that resize dynamically based on the shape of the viewport

### Example Pieces

1. Gallery: https://www.theguardian.com/global-development/gallery/2022/apr/13/game-of-confidence-nigerias-female-boxers-throw-a-punch-at-the-patriarchy-in-pictures
2. Audio: https://www.theguardian.com/news/audio/2022/apr/14/boris-johnson-broke-law-will-partygate-fines-be-undoing-podcast
3. Video: https://www.theguardian.com/uk-news/video/2022/apr/13/made-in-middlesbrough-it-takes-a-village-video

### CODE REVIEW

**Review by oliverlloyd — APPROVED** [review]
As per our discussion in Dotcom, this makes sense from our perspective. We already have a type of `MediaType` to try and handle these variations so this change seems logical

**Review by mxdvl — APPROVED** [review]

**Review by OllysCoding — APPROVED** [review]
+1 I think this change makes a lot of sense :)

**Review by sndrs — APPROVED** [review]

**Comment by sndrs** [comment]
is this still needed?

**Comment by oliverlloyd** [comment]
> is this still needed?

I think so

**Pull request merged**
